import { useEffect, useState } from "react";
import { Gift, Percent, Save, Truck, BadgeDollarSign } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "./lib/supabase";
type Settings={enabled:boolean;reward_type:"PERCENT"|"FIXED"|"FREIGHT"|"GIFT";reward_value:number;gift_description:string;validity_days:number;min_order_amount:number};
const defaults:Settings={enabled:true,reward_type:"PERCENT",reward_value:10,gift_description:"Brinde especial",validity_days:30,min_order_amount:0};
export default function FirstPurchaseSettings({ownerId}:{ownerId?:string}){
 const [value,setValue]=useState<Settings>(defaults),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 useEffect(()=>{if(!supabase||!ownerId)return;supabase.from("first_purchase_settings").select("*").eq("owner_id",ownerId).maybeSingle().then(({data,error})=>{if(error)toast.error("Não foi possível carregar a configuração",{description:error.message});else if(data)setValue({...defaults,...data});setLoading(false)});},[ownerId]);
 const save=async()=>{if(!supabase||!ownerId)return;setSaving(true);const payload={owner_id:ownerId,enabled:value.enabled,reward_type:value.reward_type,reward_value:Number(value.reward_value)||0,gift_description:value.gift_description.trim()||null,validity_days:Math.min(365,Math.max(1,Number(value.validity_days)||30)),min_order_amount:Math.max(0,Number(value.min_order_amount)||0)};const {error}=await supabase.from("first_purchase_settings").upsert(payload,{onConflict:"owner_id"});setSaving(false);if(error){toast.error("Não foi possível salvar",{description:error.message});return}setValue({...value,...payload});toast.success("Presente de primeira compra atualizado")};
 const rewardLabel=value.reward_type==="PERCENT"?"Desconto percentual":value.reward_type==="FIXED"?"Desconto em valor":value.reward_type==="FREIGHT"?"Frete grátis":"Brinde";
 return <section className="page-section"><div className="page-head"><div><p className="eyebrow">CONVERSÃO DA LOJA</p><h2>Presente de 1ª compra</h2><p>Defina o benefício que será liberado para novas clientes.</p></div><button className="primary" onClick={save} disabled={saving||loading}><Save size={16}/>{saving?"Salvando…":"Salvar configuração"}</button></div>
 <div className="panel" style={{maxWidth:820}}><div style={{display:"flex",alignItems:"center",gap:14,marginBottom:24}}><div className="brand-mark"><Gift size={21}/></div><div><strong>Popup de primeira compra</strong><p style={{margin:4}}>A cliente informa nome e WhatsApp e recebe um benefício individual, válido uma vez.</p></div></div>
 <label style={{display:"flex",alignItems:"center",gap:10,marginBottom:22}}><input type="checkbox" checked={value.enabled} onChange={e=>setValue(v=>({...v,enabled:e.target.checked}))}/> Ativar presente de primeira compra</label>
 <div className="form-grid"><label>Tipo de benefício<select value={value.reward_type} onChange={e=>setValue(v=>({...v,reward_type:e.target.value as Settings["reward_type"]}))}><option value="PERCENT">Desconto em %</option><option value="FIXED">Desconto em valor (R$)</option><option value="FREIGHT">Frete grátis</option><option value="GIFT">Brinde</option></select></label>
 {value.reward_type==="PERCENT"&&<label>Desconto (%)<input type="number" min="1" max="100" value={value.reward_value} onChange={e=>setValue(v=>({...v,reward_value:Number(e.target.value)}))}/></label>}
 {value.reward_type==="FIXED"&&<label>Desconto (R$)<input type="number" min="0" step="0.01" value={value.reward_value} onChange={e=>setValue(v=>({...v,reward_value:Number(e.target.value)}))}/></label>}
 {value.reward_type==="FREIGHT"&&<p style={{gridColumn:"1/-1",margin:0}}>O benefício cobre automaticamente o frete calculado no checkout.</p>}
 {value.reward_type==="GIFT"&&<label>Brinde oferecido<input value={value.gift_description} onChange={e=>setValue(v=>({...v,gift_description:e.target.value}))} placeholder="Ex.: Brinco delicado"/></label>}
 <label>Validade do benefício (dias)<input type="number" min="1" max="365" value={value.validity_days} onChange={e=>setValue(v=>({...v,validity_days:Number(e.target.value)}))}/></label>
 <label>Pedido mínimo (R$)<input type="number" min="0" step="0.01" value={value.min_order_amount} onChange={e=>setValue(v=>({...v,min_order_amount:Number(e.target.value)}))}/></label></div>
 <div className="panel" style={{marginTop:22,background:"#fff8fb",borderColor:"#f1d9e2"}}><div style={{display:"flex",gap:10,alignItems:"center"}}>{value.reward_type==="PERCENT"?<Percent size={18}/>:value.reward_type==="FIXED"?<BadgeDollarSign size={18}/>:value.reward_type==="FREIGHT"?<Truck size={18}/>:<Gift size={18}/>}<strong>Resumo</strong></div><p style={{margin:"10px 0 0"}}>{value.enabled?"Ativo":"Desativado"}{" · "}{rewardLabel}{value.reward_type==="PERCENT"?" de "+value.reward_value+"%":value.reward_type==="FIXED"?" de "+value.reward_value.toLocaleString("pt-BR",{style:"currency",currency:"BRL"}):value.reward_type==="GIFT"?" · "+(value.gift_description||"brinde"):""}{" · validade de "}{value.validity_days}{" dias."}</p></div>
 </div></section>;
}