import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const cors={"Access-Control-Allow-Origin":"https://violetta.com.br","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(b:unknown)=>new Response(JSON.stringify(b),{headers:{...cors,"Content-Type":"application/json"}});
const esc=(v:string)=>v.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]??c));
async function hash(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,"0")).join("")}
async function allowed(db:any,a:string,e:string,ip:string){for(const x of [a+":email:"+e,a+":ip:"+ip]){const k=await hash(x);const {data}=await db.from("auth_email_rate_limits").select("last_sent_at").eq("rate_key",k).maybeSingle();if(data?.last_sent_at&&Date.now()-new Date(data.last_sent_at).getTime()<60000)return false}return true}
async function mark(db:any,a:string,e:string,ip:string){const t=new Date().toISOString();for(const x of [a+":email:"+e,a+":ip:"+ip])await db.from("auth_email_rate_limits").upsert({rate_key:await hash(x),last_sent_at:t})}
async function send(to:string,subject:string,html:string,text:string){const key=Deno.env.get("RESEND_API_KEY");if(!key)throw new Error("mail");const r=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:"Bearer "+key,"Content-Type":"application/json"},body:JSON.stringify({from:"Violetta <contato@violetta.com.br>",to:[to],subject,html,text})});if(!r.ok)throw new Error("send")}
function mail(title:string,content:string){return '<!doctype html><html lang="pt-BR"><body style="margin:0;padding:32px 16px;background:#fff0f5;font-family:Arial;color:#332e2a"><div style="max-width:560px;margin:auto;background:#fff;border:1px solid #f1d9e2;border-radius:18px;overflow:hidden"><div style="padding:30px;text-align:center"><img src="https://violetta.com.br/logo-violetta.jpeg" width="180" style="max-width:70%;height:auto"><h1 style="color:#3a2830">'+title+'</h1></div><div style="padding:0 30px 30px">'+content+'</div><div style="border-top:1px solid #f1d9e2;padding:18px;text-align:center;color:#8a817a;font-size:12px">Violetta Jóias e Semi Joias</div></div></body></html>'}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers: cors});try{
const b=await req.json();const action=String(b?.action||"");const email=String(b?.email||"").trim().toLowerCase();const ip=req.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||"unknown";const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
if(!email.includes("@"))return json({ok:true});if(!(await allowed(db,action,email,ip)))return json({ok:true});
if(action==="signup"){const password=String(b?.password||"");const name=String(b?.name||"cliente").trim()||"cliente";const phone=String(b?.phone||"").replace(/\D/g,"");const birthday=String(b?.birthday||"");if(password.length<6)return json({ok:true});const {data:u,error:ce}=await db.auth.admin.createUser({email,password,email_confirm:false,user_metadata:{full_name:name,phone,birthday}});if(!ce&&u?.user){const {data,error}=await db.auth.admin.generateLink({type:"signup",email,options:{redirectTo:"https://violetta.com.br/minha-conta"}});if(!error&&data?.properties?.action_link){const link=data.properties.action_link;await send(email,"Confirme seu cadastro | Violetta",mail("Confirme seu cadastro",'<p>Olá, '+esc(name)+'! Falta apenas confirmar seu e-mail.</p><p style="text-align:center;margin:28px"><a href="'+link+'" style="background:#b85f7f;color:white;text-decoration:none;padding:14px 24px;border-radius:10px;font-weight:bold">Confirmar meu e-mail</a></p><p>Se você não criou esta conta, ignore este e-mail.</p>'),"Confirme seu cadastro na Violetta: "+link);await mark(db,action,email,ip)}}return json({ok:true})}
const type=action==="recovery"?"recovery":"signup";const {data,error}=await db.auth.admin.generateLink({type,email,options:{redirectTo:"https://violetta.com.br/minha-conta"}});if(!error&&data?.properties?.action_link){const link=data.properties.action_link;const name=String(data.user?.user_metadata?.full_name||"cliente");const recovery=action==="recovery";await send(email,recovery?"Redefina sua senha | Violetta":"Confirme seu cadastro | Violetta",mail(recovery?"Redefina sua senha":"Confirme seu cadastro",recovery?'<p>Recebemos uma solicitação para criar uma nova senha.</p><p style="text-align:center;margin:28px"><a href="'+link+'" style="background:#b85f7f;color:white;text-decoration:none;padding:14px 24px;border-radius:10px;font-weight:bold">Criar nova senha</a></p><p>Se você não solicitou isso, ignore este e-mail.</p>':'<p>Olá, '+esc(name)+'! Falta apenas confirmar seu e-mail.</p><p style="text-align:center;margin:28px"><a href="'+link+'" style="background:#b85f7f;color:white;text-decoration:none;padding:14px 24px;border-radius:10px;font-weight:bold">Confirmar meu e-mail</a></p>',recovery?"Crie uma nova senha na Violetta: ":"Confirme seu cadastro na Violetta: "+link);await mark(db,action,email,ip)}return json({ok:true})}catch{return json({ok:true})}});