create table if not exists public.products (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  category text not null,
  material text not null,
  cost numeric(12,2) not null default 0,
  price numeric(12,2) not null default 0,
  stock integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  phone text not null default '',
  email text not null default '',
  birthday date,
  preferences text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  date date not null default current_date,
  product_id bigint not null,
  client_id bigint not null,
  amount numeric(12,2) not null default 0,
  payment text not null,
  discount numeric(12,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cash_entries (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  date date not null default current_date,
  type text not null check (type in ('Entrada', 'Saída')),
  category text not null,
  description text not null,
  amount numeric(12,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.promotions (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  type text not null,
  value numeric(12,2) not null default 0,
  code text not null,
  ends date not null,
  active boolean not null default true,
  uses integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_owner_idx on public.products(owner_id);
create index if not exists clients_owner_idx on public.clients(owner_id);
create index if not exists sales_owner_idx on public.sales(owner_id);
create index if not exists cash_entries_owner_idx on public.cash_entries(owner_id);
create index if not exists promotions_owner_idx on public.promotions(owner_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at before update on public.products for each row execute function public.set_updated_at();
drop trigger if exists clients_set_updated_at on public.clients;
create trigger clients_set_updated_at before update on public.clients for each row execute function public.set_updated_at();
drop trigger if exists sales_set_updated_at on public.sales;
create trigger sales_set_updated_at before update on public.sales for each row execute function public.set_updated_at();
drop trigger if exists cash_entries_set_updated_at on public.cash_entries;
create trigger cash_entries_set_updated_at before update on public.cash_entries for each row execute function public.set_updated_at();
drop trigger if exists promotions_set_updated_at on public.promotions;
create trigger promotions_set_updated_at before update on public.promotions for each row execute function public.set_updated_at();

alter table public.products enable row level security;
alter table public.clients enable row level security;
alter table public.sales enable row level security;
alter table public.cash_entries enable row level security;
alter table public.promotions enable row level security;

drop policy if exists products_owner_select on public.products;
create policy products_owner_select on public.products for select to authenticated using (owner_id = auth.uid());
drop policy if exists products_owner_insert on public.products;
create policy products_owner_insert on public.products for insert to authenticated with check (owner_id = auth.uid());
drop policy if exists products_owner_update on public.products;
create policy products_owner_update on public.products for update to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
drop policy if exists products_owner_delete on public.products;
create policy products_owner_delete on public.products for delete to authenticated using (owner_id = auth.uid());

 drop policy if exists clients_owner_select on public.clients;
create policy clients_owner_select on public.clients for select to authenticated using (owner_id = auth.uid());
drop policy if exists clients_owner_insert on public.clients;
create policy clients_owner_insert on public.clients for insert to authenticated with check (owner_id = auth.uid());
drop policy if exists clients_owner_update on public.clients;
create policy clients_owner_update on public.clients for update to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
drop policy if exists clients_owner_delete on public.clients;
create policy clients_owner_delete on public.clients for delete to authenticated using (owner_id = auth.uid());

create policy sales_owner_all on public.sales for all to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy cash_entries_owner_all on public.cash_entries for all to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy promotions_owner_all on public.promotions for all to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
