-- Orders are mutated through controlled RPCs/server functions only.
-- Direct authenticated updates could otherwise alter payment/order state
-- without the transition and stock/payment safeguards.
drop policy if exists orders_owner_update on public.orders;
revoke update on public.orders from authenticated;
revoke insert on public.orders from authenticated;
revoke delete on public.orders from authenticated;

-- Payment events are server-generated and must never be writable by the client.
revoke insert, update, delete on public.payment_events from authenticated, anon;

-- Order history is generated by trusted workflows; clients only need read access.
drop policy if exists "owners can insert order history" on public.order_status_history;
revoke insert, update, delete on public.order_status_history from authenticated, anon;
