-- RBAC: proprietária, desenvolvedor e vendedora
create or replace function private.get_store_role(p_owner_id uuid)
returns text language sql stable security definer set search_path=''
as $$ select case when auth.uid() is null then null when auth.uid()=p_owner_id then 'owner' else (select m.role from public.store_memberships m where m.owner_id=p_owner_id and m.user_id=auth.uid() and m.active=true order by m.created_at limit 1) end $$;

create or replace function private.has_store_role(p_owner_id uuid,p_roles text[])
returns boolean language sql stable security definer set search_path=''
as $$ select coalesce(private.get_store_role(p_owner_id)=any(p_roles),false) $$;

alter table public.store_memberships drop constraint if exists store_memberships_role_check;
alter table public.store_memberships add constraint store_memberships_role_check check (role in ('developer','seller'));
update public.store_memberships set role='developer' where role='manager';

create table if not exists public.audit_logs(
 id bigint generated by default as identity primary key,
 owner_id uuid not null,
 actor_user_id uuid not null,
 action text not null,
 table_name text not null,
 row_id text,
 old_data jsonb,
 new_data jsonb,
 created_at timestamptz not null default now()
);
alter table public.audit_logs enable row level security;
drop policy if exists audit_logs_developer_read on public.audit_logs;
create policy audit_logs_developer_read on public.audit_logs for select to authenticated using(private.has_store_role(owner_id,array['developer']));
create index if not exists audit_logs_owner_created_idx on public.audit_logs(owner_id,created_at desc);

create or replace function private.write_audit_log()
returns trigger language plpgsql security definer set search_path=''
as $$
declare v_owner uuid; v_row_id text;
begin
 v_owner:=coalesce((case when TG_OP='DELETE' then to_jsonb(OLD)->>'owner_id' else to_jsonb(NEW)->>'owner_id' end)::uuid,null);
 if v_owner is null or auth.uid() is null then return coalesce(NEW,OLD); end if;
 v_row_id:=coalesce(to_jsonb(NEW)->>'id',to_jsonb(OLD)->>'id');
 insert into public.audit_logs(owner_id,actor_user_id,action,table_name,row_id,old_data,new_data)
 values(v_owner,auth.uid(),TG_OP,TG_TABLE_NAME,v_row_id,case when TG_OP in('UPDATE','DELETE') then to_jsonb(OLD) end,case when TG_OP in('INSERT','UPDATE') then to_jsonb(NEW) end);
 return coalesce(NEW,OLD);
end $$;

do $$
declare t text;
begin
 foreach t in array array['products','sales','cash_entries','clients','promotions','public_products','orders','order_items','storefront_settings'] loop
  execute format('drop trigger if exists audit_%I on public.%I',t,t);
  execute format('create trigger audit_%I after insert or update or delete on public.%I for each row execute function private.write_audit_log()',t,t);
 end loop;
end $$;

drop policy if exists products_owner_all on public.products;
create policy products_staff_select on public.products for select to authenticated using(private.has_store_role(owner_id,array['owner','developer','seller']));
create policy products_staff_insert on public.products for insert to authenticated with check(private.has_store_role(owner_id,array['owner','developer','seller']));
create policy products_owner_developer_update on public.products for update to authenticated using(private.has_store_role(owner_id,array['owner','developer'])) with check(private.has_store_role(owner_id,array['owner','developer']));
create policy products_owner_developer_delete on public.products for delete to authenticated using(private.has_store_role(owner_id,array['owner','developer']));

drop policy if exists sales_owner_all on public.sales;
create policy sales_staff_select on public.sales for select to authenticated using(private.has_store_role(owner_id,array['owner','developer','seller']));
create policy sales_staff_insert on public.sales for insert to authenticated with check(private.has_store_role(owner_id,array['owner','developer','seller']));
create policy sales_owner_developer_update on public.sales for update to authenticated using(private.has_store_role(owner_id,array['owner','developer'])) with check(private.has_store_role(owner_id,array['owner','developer']));
create policy sales_owner_developer_delete on public.sales for delete to authenticated using(private.has_store_role(owner_id,array['owner','developer']));

drop policy if exists clients_owner_all on public.clients;
create policy clients_staff_select on public.clients for select to authenticated using(private.has_store_role(owner_id,array['owner','developer','seller']));
create policy clients_staff_insert on public.clients for insert to authenticated with check(private.has_store_role(owner_id,array['owner','developer','seller']));
create policy clients_owner_developer_update on public.clients for update to authenticated using(private.has_store_role(owner_id,array['owner','developer'])) with check(private.has_store_role(owner_id,array['owner','developer']));
create policy clients_owner_developer_delete on public.clients for delete to authenticated using(private.has_store_role(owner_id,array['owner','developer']));

drop policy if exists cash_entries_owner_all on public.cash_entries;
create policy cash_owner_developer_all on public.cash_entries for all to authenticated using(private.has_store_role(owner_id,array['owner','developer'])) with check(private.has_store_role(owner_id,array['owner','developer']));
drop policy if exists promotions_owner_all on public.promotions;
create policy promotions_owner_developer_all on public.promotions for all to authenticated using(private.has_store_role(owner_id,array['owner','developer'])) with check(private.has_store_role(owner_id,array['owner','developer']));
drop policy if exists orders_owner_all on public.orders;
create policy orders_owner_developer_all on public.orders for all to authenticated using(private.has_store_role(owner_id,array['owner','developer'])) with check(private.has_store_role(owner_id,array['owner','developer']));
drop policy if exists stock_movements_owner_select on public.stock_movements;
create policy stock_movements_owner_developer_select on public.stock_movements for select to authenticated using(private.has_store_role(owner_id,array['owner','developer']));

create or replace function private.create_manual_sale_service(p_date date,p_product_id bigint,p_client_id bigint,p_amount numeric,p_payment text,p_discount numeric default 0,p_quantity integer default 1)
returns jsonb language plpgsql security definer set search_path=''
as $$
declare v_owner uuid:=private.get_store_owner_id(); v_product public.products%rowtype; v_sale public.sales%rowtype; v_cash public.cash_entries%rowtype; v_before integer;
begin
 if v_owner is null or not private.has_store_role(v_owner,array['owner','developer','seller']) then raise exception 'Sem permissão para registrar venda'; end if;
 if p_amount is null or p_amount < 0 then raise exception 'Valor da venda inválido'; end if;
 if p_discount is null or p_discount < 0 then raise exception 'Desconto inválido'; end if;
 if p_quantity is null or p_quantity < 1 then raise exception 'Quantidade inválida'; end if;
 select * into v_product from public.products where id=p_product_id and owner_id=v_owner for update;
 if not found then raise exception 'Produto não encontrado'; end if;
 if v_product.stock < p_quantity then raise exception using message='Estoque insuficiente. Disponível: '||v_product.stock; end if;
 v_before:=v_product.stock;
 insert into public.sales(owner_id,date,product_id,client_id,amount,payment,discount,channel,quantity) values(v_owner,p_date,p_product_id,p_client_id,p_amount,p_payment,p_discount,'PRESENCIAL',p_quantity) returning * into v_sale;
 update public.products set stock=stock-p_quantity,updated_at=now() where id=v_product.id and owner_id=v_owner returning * into v_product;
 insert into public.stock_movements(owner_id,product_id,movement_type,quantity,stock_before,stock_after,reason,sale_id) values(v_owner,v_product.id,'SALE',-p_quantity,v_before,v_product.stock,'Venda presencial',v_sale.id);
 insert into public.cash_entries(owner_id,date,type,category,description,amount,sale_id) values(v_owner,p_date,'Entrada','Venda','Venda presencial #'||right(v_sale.id::text,8),p_amount,v_sale.id) returning * into v_cash;
 return jsonb_build_object('sale',to_jsonb(v_sale),'cash',to_jsonb(v_cash),'product',to_jsonb(v_product));
end $$;